language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t strik3ria/docker-react:latest .

script:
  - docker run -e CI=true strik3ria/docker-react:latest npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker3"
  env: "Docker3-env"
  bucket_name: "elasticbeanstalk-us-east-1-304196588227"
  bucket_path: "docker3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
